### ISSUE TITLE
Invalid results when converting bootstrap

### ISSUE THREAD

**Issue by BattleBrisket** [paulcpederson/sass2stylus#1]
The [Bootstrap Sass set](https://github.com/twbs/bootstrap-sass) doesn't make its way cleanly into Stylus. I would encourage you to do some testing there, as I'm sure I'm not the only one who's looking for a converter simply to get Bootstrap into Stylus.

Here's a few simple examples:

#### bootstrap/mixins/hide-text
```
# Sass
@mixin hide-text() {
  font: #{0/0} a;
  color: transparent;
  text-shadow: none;
  background-color: transparent;
  border: 0;
}

# Resulting Stylus
hide-text()
  font: {0 / 0} a  # breaks on this line
  color: transparent
  text-shadow: none
  background-color: transparent
  border: 0
```

#### bootstrap/mixins/responsive-visibility
```
# Sass
@mixin responsive-visibility($parent) {
  #{$parent} {
    display: block !important;
  }
  table#{$parent}  { display: table; }
  tr#{$parent}     { display: table-row !important; }
  th#{$parent},
  td#{$parent}     { display: table-cell !important; }
}

# Resulting Stylus
responsive-visibility($parent)
  {$parent}
    display: block !important
  table{$parent}
    display: table
  tr{$parent}
    display: table-row !important
  th{$parent},
    display: table-cell !important
# removed definition for td#{$parent}
```

**Comment by paulcpederson** [comment]
That notation isn't in that file anymore. As per https://github.com/twbs/bootstrap-sass/commit/0445445727423f03d0dfc457560250172a7dcfb3 they're removed the escaping there. I'm going to close this, feel free to reopen.
