### ISSUE TITLE
Reason for disabled functions

### ISSUE THREAD

**Issue by prabinv** [paulcpederson/sass2stylus#3]
Hi,
We were looking at using sass2stylus for converting Sass files to stylus in our project. During the compilation we came across some functions (viz, Compass functions) which were not converted. These functions were defined in the functions.yml file. Is there any reason for disabling these functions? Is it not possible to convert these functions to Stylus mixins?

disabled_functions:
  - adjust-color
  - adjust-hue
  - append
  - call
  - change-color
  - comparable
  - fade-in
  - fade-out
  - feature-exists
  - function-exists
  - global-variable-exists
  - ie-hex-str
  - index
  - keywords
  - list-separator
  - map-get
  - map-remove
  - mixin-exists
  - nth
  - opacify
  - percentage
  - quote
  - random
  - scale-color
  - str-index
  - str-insert
  - str-length
  - str-slice
  - to-lower-case
  - to-upper-case
  - transparentize
  - unique-id
  - unitless
  - variable-exists
  - zip

Thanks!!

**Comment by paulcpederson** [comment]
sass2stylus.com had these disabled and I'm mostly copying them. I just assumed they were impossible to translate, but IDK.

**Comment by paulcpederson** [comment]
@prabinv OK I just looked into it a bit further. Looks like the mojo tech guys added this file here: https://github.com/mojotech/sass2stylus/commit/9fae83ee4466803f27f4fcd8a2159c82ade5402c

The reason being that they aren't supported in stylus. I've going to close this, feel free to reopen if that doesn't answer your question.
