### ISSUE TITLE
Regular CSS @import produces bad string

### ISSUE THREAD

**Issue by piknik** [paulcpederson/sass2stylus#4]
I have a SCSS file with the following contents:
```
@import "themes/default";
@import url(https://fonts.googleapis.com/css?family=Fredericka+the+Great);
```
which outputs the following after running the conversion:
```
@import 'themes/default'
@import #<Sass::Script::Tree::Literal:0x00000002120230>
```
I suppose that sass2stylus is mistaking the regular CSS @import *url* for some kind of sass function.
Running sass2stylus version 0.0.1

**Comment by paulcpederson** [comment]
@piknik did you try putting quotes around the url?

**Comment by paulcpederson** [comment]
I actually just tried it locally and it does work if you quote it. Feel free to reopen if that doesn't work for you.
